### ISSUE TITLE
update benchmarks

### ISSUE THREAD

**Issue by Austernpilz** [seqan/raptor#303]
--rearrange-user-bins is deprecated

<img width="1046" alt="grafik" src="https://user-images.githubusercontent.com/87067941/236258353-ba2cda62-068b-4d60-82b1-a4dfacc96992.png">

**Comment by eseiler** [comment]
These scripts were used with https://github.com/seqan/raptor/tree/560a45f

I'm not sure yet if I intend to maintain the scripts, since they reflect what we did for the paper, and are not meant as a benchmark. (Also, they are hard to maintain without CI).

We will add general purpose benchmarks in the future.
